version: '3'

services:
  postgres:
    container_name: crud_db
    image:  postgres
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crud_db
      POSTGRES_PASSWORD: postgres


volumes:
  postgresdata:
